version: '3.4'

services:
  dockerapp:
    image: ${DOCKER_REGISTRY-}dockerapp
    build:
      context: .
      dockerfile: DockerApp/Dockerfile
  SHAHIDPC:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass@123
  WebApi:
        container_name: WebApiContainer
        image: ${DOCKER_REGISTRY-}dockerapp
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: dockerapp/Dockerfile
        depends_on:
            - SHAHIDPC 